export type ReceiptCreate = {
  item_code: string;
  item_name: string;
  lot_number: string;
  maker_lot_number: string;
  order_number: string;
  branch_number: number;
  partial_number: number;
  work_center: string;
  supplier: string;
  supplier_name?: string | null;
  storage_location: string;
  expiration_date?: string | Date | null;
  arrival_date: string | Date;
  arrival_time: string;
  color_index?: string | null;
  delivery_order_number: string;
  delivery_order_date: string | Date;
  item_category?: string | null;
  custom_doc_number?: string | null;
  custom_doc_type?: string | null;
  custom_doc_date?: string | Date | null;
  grade?: string | null;
  actual_qty: number;
  gross_weight?: number | null;
  unit: string;
  sender?: string | null;
  material_status?: string;
  aju_number?: string | null;
  remarks?: string | null;
  remark_general?: string | null;
  pallet_number?: string | null;
  po_number?: string | null;
  packing_slip: number;
  id: string;
};

export type Incoming = {
  order_number: string;
  po_number?: string | null;
  note?: string | null;
  general_note?: string | null;
  item_code: string;
  item_name: string;
  lot_number: string | null;
  maker_lot_number: string | null;
  item_category: string;
  branch_number: number;
  partial_number: number;
  schedule_qty: number;
  actual_qty: number;
  unit: string;
  storage_location: string;
  storage_location_name: string;
  work_center: string;
  work_center_name: string;
  supplier: string;
  supplier_name: string;
  material_status: string | null;
  grade: string | null;
  color_index: string | null;
  currency: string | null;
  delivery_date: Date;
};
