export const fieldLabels: Record<string, string> = {
  item_code: "Item Code",
  item_name: "Item Name",
  lot_number: "Lot Number",
  maker_lot_number: "Business Partner",
  order_number: "Order Number",
  branch_number: "Branch Number",
  partial_number: "Partial Number",
  work_center: "Work Center",
  supplier: "Supplier",
  storage_location: "Storage Location",
  expiration_date: "Expiration Date",
  arrival_date: "Arrival Date",
  arrival_time: "Arrival Time",
  color_index: "Color Index",
  delivery_order_number: "Delivery Order Number",
  delivery_order_date: "Delivery Order Date",
  item_category: "Item Category",
  custom_doc_number: "BC No.",
  custom_doc_type: "BC Type",
  custom_doc_date: "BC Date",
  grade: "Grade",
  actual_qty: "Received Quantity",
  unit: "Unit",
  sender: "Sender",
  material_status: "Material Status",
  aju_number: "AJU No.",
  packing_slip: "Packing Slip",
  gross_weight: "Gross Weight",
};
